stages:
  - build
  - test

build_gcc:
  stage: build
  image: gcc
  before_script:
    - apt-get update
    - apt-get install -y cmake libssl-dev
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

build_clang:
  stage: build
  image: ubuntu:focal
  before_script:
    - apt-get update
    - apt-get install -y clang cmake libssl-dev
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

test_gtest:
  stage: test
  image: mink0/gtest
  before_script:
    - apk add openssl-dev
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make 
    - cd test
    - ./aoc15_d01_unittest --gtest_output=xml:gtest-report-01.xml
    - ./aoc15_d02_unittest --gtest_output=xml:gtest-report-02.xml
    - ./aoc15_d03_unittest --gtest_output=xml:gtest-report-03.xml
    - ./aoc15_d04_unittest --gtest_output=xml:gtest-report-04.xml
  artifacts:
    reports:
      junit:
        - build/test/gtest-report-01.xml
        - build/test/gtest-report-02.xml
        - build/test/gtest-report-03.xml
        - build/test/gtest-report-04.xml
