stages:
  - build
  - test

build_gcc:
  stage: build
  image: gcc
  before_script:
    - apt-get update
    - apt-get install -y cmake libssl-dev
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

build_clang:
  stage: build
  image: ubuntu:focal
  before_script:
    - apt-get update
    - apt-get install -y clang cmake libssl-dev
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

test_gtest:
  stage: test
  image: mink0/gtest
  before_script:
    - apk add openssl-dev
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make check
  artifacts:
    reports:
      junit:
        - build/test/*-report.xml
