language: cpp
os: linux
dist: focal

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      name: GCC
      compiler:
        - gcc
      script:
        - mkdir build && cd build
        - cmake ../
        - make

    - stage: build
      name: Clang
      compiler:
        - clang
      script:
        - mkdir build && cd build
        - cmake ../
        - make

    - stage: build
      name: Clang-Tidy
      compiler:
        - gcc
      before_install:
        - sudo apt-get -y update && sudo apt-get -y upgrade
        - sudo apt-get install clang-tidy
        - clang-tidy --version
      script:
        - mkdir build && cd build
        - cmake "-DCMAKE_CXX_CLANG_TIDY=clang-tidy;--header-filter=.*;--warnings-as-errors=*" ../
        - make

    - stage: build
      name: Cppcheck
      compiler:
        - gcc
      before_install:
        - sudo apt-get -y update
        - sudo apt-get install cppcheck
      script:
        - mkdir build && cd build
        - cmake "-DCMAKE_CXX_CPPCHECK=cppcheck;--std=c++17;--error-exitcode=1" ../
        - make

    - stage: test
      name: Unit test
      compiler:
          gcc
      before_install:
        - sudo apt-get -y update
        - sudo apt-get install libgtest-dev
      script:
        - mkdir build && cd build
        - cmake ../
        - make check
