language: cpp
os: linux
dist: bionic

stages:
  - build
  - test


jobs:
  include:
    - stage: build
      name: GCC-10
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - gcc-10
      env:
        - CC=gcc-10
        - CXX=g++-10
      script:
        - mkdir build && cd build
        - cmake ../
        - make

    - stage: build
      name: Clang-11
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-11
          packages:
            - clang-11
      env:
        - CC=clang-11
        - CXX=clang++-11
      script:
        - mkdir build && cd build
        - cmake ../
        - make

    - stage: build
      name: Clang-Tidy
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
            - clang-tidy-10
      env:
        - CC=clang-10
        - CXX=clang++-10
      script:
        - mkdir build && cd build
        - clang-tidy --version
        - clang-tidy --dump-config
        - cmake "-DCMAKE_CXX_CLANG_TIDY=clang-tidy-10;--header-filter=.*;--warnings-as-errors=*" ../
        - make

    - stage: build
      name: Cppcheck
      compiler:
        - gcc
      before_install:
        - sudo apt-get -y update
        - sudo apt-get install cppcheck
      script:
        - mkdir build && cd build
        - cmake "-DCMAKE_CXX_CPPCHECK=cppcheck;--std=c++17;--error-exitcode=1" ../
        - make

    - stage: test
      name: Unit test
      compiler:
          gcc
      before_install:
        - sudo apt-get -y update
        - sudo apt-get install libgtest-dev
      script:
        - mkdir build && cd build
        - cmake ../
        - make check
