language: cpp
os: linux
dist: focal

stages:
  - build
  - test


jobs:
  include:
    - stage: build
      name: GCC-9
      addons:
        apt:
          packages:
            - g++-9
            - gcc-9
      env:
        - CC=gcc-9
        - CXX=g++-9
      script:
        - mkdir build && cd build
        - cmake ../
        - make

    - stage: build
      name: GCC-10
      addons:
        apt:
          packages:
            - g++-10
            - gcc-10
      env:
        - CC=gcc-10
        - CXX=g++-10
      script:
        - mkdir build && cd build
        - cmake ../
        - make

    - stage: build
      name: Clang-10
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
          packages:
            - clang-10
      env:
        - CC=clang-10
        - CXX=clang++-10
      script:
        - mkdir build && cd build
        - cmake ../
        - make

    - stage: build
      name: Clang-11
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
          packages:
            - clang-11
      env:
        - CC=clang-11
        - CXX=clang++-11
      script:
        - mkdir build && cd build
        - cmake ../
        - make

    - stage: build
      name: Clang-Tidy
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
          packages:
            - clang-10 clang-tidy-10
      env:
        - CC=clang-10
        - CXX=clang++-10
      script:
        - mkdir build && cd build
        - clang-tidy --version
        - clang-tidy --dump-config
        - cmake "-DCMAKE_CXX_CLANG_TIDY=clang-tidy-10;--header-filter=.*;--warnings-as-errors=*" ../
        - make

    - stage: build
      name: Cppcheck
      addons:
        apt:
          packages:
            - g++-10
            - gcc-10
            - cppcheck
      env:
        - CC=gcc-10
        - CXX=g++-10
      script:
        - mkdir build && cd build
        - cmake "-DCMAKE_CXX_CPPCHECK=cppcheck;--std=c++17;--error-exitcode=1" ../
        - make

    - stage: test
      name: Unit test
      addons:
        apt:
          packages:
            - g++-10
            - gcc-10
            - libgtest-dev
      env:
        - CC=gcc-10
        - CXX=g++-10
      script:
        - mkdir build && cd build
        - cmake ../
        - make check
